### ISSUE TITLE
New FSI panel

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-fsharp#104]
Discussion moved from #103

@tpetricek:
"Aside, do you think it's a good idea to print the F# code sent to F# Interactive in the window? Visual Studio does not do that and I'm quite happy with that.

That said, if the FSI window was HTML frame, we could create some really fancy expandable HTML gadget that would be hidden by default and you could click on it to see the full output. How hard would it be to change the FSI window into a read-only HTML window with some `<pre>` tags in it?"

My response:
"Personally, I like printing input code in FSI panel, but idea to make more fancy panel with for example possibility to hide / expand some parts of communication sounds good for me. Only drawback I see is that right now since FSI panel is text editor, user can easily save it to file to have dump of whole FSI session - I guess same would be possible with custom panel but it will require some work.

I guess upgrading of FSI panel should be discussed separately from this PR, so feel free to create issue for it."

**Comment by tpetricek** [comment]
I think there are at least two different ways of looking at the FSI panel. Both of them make sense, and nobody knows which one is better :-). 

 - **Output panel** - the idea is that FSI is just for output. You do not typically write any code there - you just see the output of things from a script file. In this view, you do not need IntelliSense in the FSI panel, but you would probably want richer (say, HTML) output with charts.

 - **Full editor** - you should be able to do most of your work in FSI (I think R/Mathematica/IPython Notebook all kind of do this). You also have all of the above (with rich output), but the FSI is full editor with auto-complete and everything and it makes sense to serialize your entire session etc. You probably want to see all the code in this case. 

The nice thing about treating FSI as output panel is that you really end up editing code in more reusable script files. But the nice thing about full editor is that you don't even need script files for some tasks.

I think quite a few people coming from "full editor" backgrounds expect to be able to use it in that way, so supporting that model would be nice (that said, I think it is hard - I think it would require changes to F# interactive and the compiler service). 

I guess the "full editor" mode is nicer because you see what is in the scope. With "output window", there is a mismatch between variables that are syntactically in scope and things that are defined, which can be confusing with FSI.

I would be really curious to hear what other people think about this. What are all the possible ways of using REPL?

**Comment by rkeurel** [comment]
I like the idea of a full editor mode since I feel it would make interactive programming a bit more streamlined. Even nicer, something like Scala Worksheets in Eclipse and Inline Evaluation in LightTable would allow the developer to do program interactively directly inside the file instead of a REPL session which forces you copy the code in to eval and out to save.

**Comment by tpetricek** [comment]
I would add inline evaluation as another mode:

 * **Inline evaluation** - You do not really have a separate panel with the results, but instead see the outputs embedded in the script editor. This is quite close to having editor in the FSI panel, but it works the other way round - rather than adding editor to FSI, it adds FSI outputs to the editor.

**Comment by cloudRoutine** [comment]
**Like [Xamarin sketches](http://developer.xamarin.com/guides/cross-platform/sketches/introduction/)?**

![Image of Sketch](http://developer.xamarin.com/guides/cross-platform/sketches/introduction/Images/Overview001.png)

**Like [Light Table](http://lighttable.com/)?**

![Image of Lighttable](https://i.imgur.com/Yt8KRAq.gif)

**Like [Alive](https://comealive.io/) ?**

![alivedemo](https://cloud.githubusercontent.com/assets/680051/9070015/feb33ab4-3aba-11e5-954a-365383bfb35b.gif)

**Like the [Wolfram Language](https://www.wolfram.com/language/)?**

![wolframlang](https://cloud.githubusercontent.com/assets/680051/9070290/bba21cac-3abc-11e5-8883-8b42ece357b5.gif)

some other approach?

**Comment by 7sharp9** [comment]
All of the above require "tweaks" to the compiler service to work optimally...

**Comment by tpetricek** [comment]
Yeah, that's partly why I like the idea of the output-only style of things - because it's one that we can actually implement pretty well without doing some (potentially) complex changes to the compiler.

It's tricky though - there is a lot of options in this space - and making some choices makes it hard to go in other directions...

**Comment by Krzysztof-Cieslak** [comment]
OK, I think that we have here 2 separate ideas - first is FSI Panel and whether it should be read only or full editor. For me inline evaluation could be implemented as completely separate feature ( something like Alive when You can turn it for given file and You decide when to evaluate) build on top of text editor rather than FSI panel.

Personally I think that read only FSI panel is (at least right now) better idea - for full editor mode we would need to implement all features that are build on top of text editor, build our own text editor control since it would need to allow both typing code in and showing our nice html output etc. It's not trivial task and I don't see lot of advantages over read only panel. For read only panel we only need to handle display of output - which is much less work.

Building richer HTML based panel for FSI is definitely good idea - we could provide features as hiding / minimizing of input code, tooltips, display images (if someone smart have an idea how to do it), saving output as HTML page etc.

Inline evaluation is for sure interesting, but in my opinion it should not be directly connected with FSI panel. It's something we can investigate but as Dave said - it would require changes to compiler services ( I guess building tool with standard I/O interface which would use compiler services and add stuff which we need would be necessary). But that's not a feature I want to put most effort into it right now, however if someone is interested in implementing it feel free to do so ;)

**Comment by 7sharp9** [comment]
Focus on what works, we don't really have a more advanced inline generator at present. I could probably help with that at some point though.

**Comment by panesofglass** [comment]
Not sure this is the right place, but the FSI panel on my Mac cannot find mono or fsharpi, even though both are on my path, and I've set the Mono path to the Xamarin installation. Ideas?

**Comment by Krzysztof-Cieslak** [comment]
@panesofglass: Can You please create separate issue for this? This topic is rather for discussion about possible future enhancements, not for bug discussion :)
