### ISSUE TITLE
Test Runner?

### ISSUE THREAD

**Issue by StachuK1992** [ionide/ionide-fsharp#148]
I'm a bit (very) naive of this whole Atom and Ionide thing. It all seems very exciting, though!

I'm planning to give a hands-on-lab in November, and as part of this I'd love to teach testing through F#.

Having custom Yeoman packages (or whatever they're called) for different sections throughout the hands on lab seems like an obvious choice, but I'm not sure how testing can be a part of this.

Is this a FAKE thing? Should I go look in that direction somewhere?

Bonus points:
If running F# code with F# tests is possible, what about testing C# code with F# tests?

Thanks!

**Comment by Krzysztof-Cieslak** [comment]
There is no specific "test runner" right now in Ionide, however it's really easy to create FAKE targets for testing and run those using Ionide, so I think this is good way of looking at this problem. On the other hand this approach has some problems - there is no as nice UI as in Visual Studio / Xamarin Studio test runners - instead of nice red/green notification for each test user needs to go through FAKE output and check out which test failed etc. so it might not be best choice for workshop / hands-on-lab for novice people.

And it definitely is possible to test C# code with F# test without any problems - F# test project reference C# code project, and it JustWorks™
