### ISSUE TITLE
Autocomplete notworking 1.7.0 Windows 10 Visual Studio Code

### ISSUE THREAD

**Issue by CalamityLorenzo** [ionide/ionide-fsharp#232]
Hi,
Auto complete isn't working at all for me.
It just displays the 'loading..' box when I hit ctrl+space.
Code runs in the FSI instance (14.0.23413.0), just the auto complete missing.
If I use c# or edit my json files, then autocomplete works
On my other machine (same config) the plugin works fine..

**Comment by ReverseBlade** [comment]
This issue happens again. The problem is on one of my machines I have only VS 2015 and there this problem happens. On the other one I have both VS 2013 and 2015 installed. The problem does not occur there.
 After digging the issue I worked it around by changing the file FsAutoComplete.Suave.exe.config
 below
```
 <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Framework" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
```


Change 12.0.0.0 to 14.0.0.0 for both places like:
 <bindingRedirect oldVersion="0.0.0.0-14.0.0.0" newVersion="14.0.0.0" />

 I think the plugin installation should detect which version is installed on the machine If only VS 2015 installed then version 12 will be absent but only version 14.

**Comment by Krzysztof-Cieslak** [comment]
Have you tried removing this `bindingRedirect` completely? This may also work.

**Comment by CalamityLorenzo** [comment]
The machine that's not working does indeed only have VS2015 installed.
Changing and/or deleteing the `bindingRedirect` in FsAutoComplete.Suave.exe.config as described above fixed the issue.
Just to be explicit, the file is found in `extensions\Ionide.Ionide-fsharp-1.7.0\bin`
Thanks very much
