### ISSUE TITLE
Nuget references without Yeoman

### ISSUE THREAD

**Issue by ccarnero** [ionide/ionide-fsharp#237]
Have a problem with ionide. I want to create a project without F# Yeoman, I want a more "clean" approach. So, I created this sample app with PAKET and FAKE only and after:

1 - paket update
2 - build 

I can run my program and it works great!!

But my problem, is that Atom does not recognize nuget references such as RabbitMQ.Client

<img width="797" alt="screen shot 2016-05-31 at 2 45 29 pm" src="https://cloud.githubusercontent.com/assets/911310/15684711/b53e96fa-273e-11e6-9346-6b36b4a53a0f.png">

Is there something I can do to fix it?

My platform settings are: 
- OSX 10.11.5
- ATOM 1.7.4
- Mono JIT compiler version 4.2.2
- IONIDE 1.9.1

Thanks
Christian
[rabbit.zip](https://github.com/ionide/ionide-fsharp/files/291799/rabbit.zip)

**Comment by rmunn** [comment]
Short version: you need an `.fsproj` file so that the autocomplete, type tooltips, and other nice features will work. If you don't want to make one from scratch (I wouldn't blame you), you should be able to copy an `.fsproj` file from just about any other project and adjust it to your needs. Try borrowing one from Project Scaffold and see if that works for you:

https://github.com/fsprojects/ProjectScaffold/

Longer version will have to wait until later when I have a lot more time.

**Comment by ccarnero** [comment]
I understand, thanks for your time.
